work_dir: 3Dwork/BACKBONE/Tmsg3dSmsg3d/20230513

weights: H:\ntu_paper_data\weight_server_to_local\MS-G3D-master\ablation\weights\weights-45-42137.pt
#checkpoint: model_f/work/20220830/20220830_1/checkpoint/checkpoint-96-fwbz64-60096.pt

# feeder
feeder: feeder.feeder_npy.Feeder
train_feeder_args:
#  data_path: H:\ntu_paper_data\ntu_sub\v5 0-59\val_data_joint.npy
#  label_path: H:\ntu_paper_data\ntu_sub\v5 0-59\val_label.pkl
  data_path: H:\ntu_paper_data\ntu_sub\v5 0-59\train_data_joint.npy
  label_path: H:\ntu_paper_data\ntu_sub\v5 0-59\train_label.pkl
  debug: False

test_feeder_args:
  data_path: H:\ntu_paper_data\ntu_sub\v5 0-59\val_data_joint.npy
  label_path: H:\ntu_paper_data\ntu_sub\v5 0-59\val_label.pkl
  debug: False


# stumodel
stu_model: StudentModel2.model.Model
stu_model_args:
  num_class: 60
  num_point: 25
  num_person: 2
  in_channels: 3
#  graph: graph.ntu_rgb_d.AdjMatrixGraph
#  num_gcn_scales: 13     # `num_scales` == `K + 1` in the paper，ms_gcn中要用到
#  num_g3d_scales: 6


tea_model: TeacherModel.MSG3D.msg3d.Model
tea_model_args:
  num_class: 60
  num_point: 25
  num_person: 2
  num_gcn_scales: 13     # `num_scales` == `K + 1` in the paper，ms_gcn中要用到
  num_g3d_scales: 6       #远程连接个数
  graph: graph.ntu_rgb_d.AdjMatrixGraph

final_model: StudentModel.stufinall.Final
finall_model_args:
  inchannel: 384
  num_class: 60


# optim
weight_decay: 0.0004
base_lr: 0.5
step: [15,30,45]


# training
num_epoch: 60
device: [0]
batch_size: 32
forward_batch_size: 32
test_batch_size: 32
nesterov: True
